theme: jekyll-theme-minimal
title: Julia's Collection of Creative Writing
description: a little corner of the internet for my collection of poetry and creative works :-)
logo: /assets/images/IMG_6134.JPG
url: "https://jutabaga.github.io"
